name: accessibility_tools
description: Checkers and tools to ensure your app is accessible to all. Ensures your app is accessible from day one, by checking your interface as you build it.
version: 2.1.0
homepage: https://github.com/rebelappstudio/accessibility_tools/

environment:
  sdk: ">=2.18.4 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies: 
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
