name: accessibility_tools
description: Checkers and tools to ensure your app is accessible to all. Ensures your app is accessible from day one, by checking your interface as you build it.
version: 2.5.0
homepage: https://github.com/rebelappstudio/accessibility_tools/
topics:
  - accessibility
  - a11y
  - ui

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
