name: accessibility_tools
description: Checkers and tools to ensure your app is accessible to all.
version: 0.0.1-dev.0
homepage: https://github.com/rebelappstudio/accessibility_tools/

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  dart_code_metrics: ^5.2.1
